### ISSUE TITLE
Ignore simple errors from posting

### ISSUE THREAD

**Issue by Rithari** [Rithari/OnePlusBot#106]
Right now, errors that are unecessary and easily figured out are posted to the channel as seen in the screenshot. 

![Screenshot_20190820-003412__01](https://user-images.githubusercontent.com/22421051/63304148-6090a380-c2e2-11e9-95f1-e835b886a0d3.jpg)

Simple errors like that should suppress the error message and limit themselves at adding a reaction.

**Comment by OneNormalUsername** [comment]
I actually think it should be kept as new users wanting to use `report` command might not be aware they have to provide a reason if they only see a warning emote in reaction to their message.

Unless you remind it in #info channel ?

**Comment by Rithari** [comment]
Using the help command should provide all necessary parameters. Reasons are optional for reports.

**Comment by OneNormalUsername** [comment]
Oh all right then I thought reason was mandatory because of your message introducing feature https://canary.discordapp.com/channels/378969558574432277/378970732601802760/582910369186709504

Help command would need to be updated as it doesn't seem to work as of now though https://canary.discordapp.com/channels/378969558574432277/420347617860517908/613145606604718085

**Comment by Rithari** [comment]
Help command works, your syntax is incorrect.

**Comment by OneNormalUsername** [comment]
Oh lol modules used to be called like the commands sorry for bothering
